### ISSUE TITLE
Module not found: Can't resolve 'react-router-dom'

### ISSUE THREAD

**Issue by ashutoshkarwa18** [shubham-wawale/pawpet-frontend#3]
//=========App.js file=========

//dependencies
import React, { Component } from 'react';
import { BrowserRouter as Router, Route } from 'react-router-dom';

//components
import Header from "./Header";
import Review from "./Review";
import Info from "./Info";
import Remain from "./Remain";
import Footer from "./Footer";
import Navbar from "./Navbar";

//includes
import '../../../public/css/kdg-fonts.css';
import '../../../public/css/normalize.css';
import '../../../public/css/responsive.css';
import '../../../public/css/say-my-name.css';
import '../../../public/css/style.css';

//Run
class App extends Component {
  render() {
    return (
      <Router>
        <div className="App">
          <Route path='*' component={Header} />
          <Route path='*' component={Footer} />
          <Route exact path='/' component={Home} />
          <Route exact path='/studenten' component={Review} />
          <Route exact path='/studenten/:id' component={Remain} />
          <Route exact path='/beheer' component={Info} />
          <Route exact path='/beheer/add' component={Navbar} />
          <Route exact path='/oefenen' component={Footer} />
        </div>
      </Router>
    );
  }
}

export default App;

//=========appfolder/package.json file=========

{
  "name": "saymyname",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^16.7.0",
    "react-dom": "^16.7.0",
    "react-scripts": "2.1.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ],
  "devDependencies": {
    "gulp": "^4.0.0",
    "gulp-changed": "^3.2.0",
    "gulp-clean-css": "^4.0.0",
    "gulp-rename": "^1.4.0",
    "gulp-sass": "^4.0.2",
    "gulp-uglify": "^3.0.1"
  }
}

**Comment by akansha-tri** [comment]
Run the following command in the terminal **"npm i react-router-dom"** the issue will get resolved.
OR
Either run **yarn** or **npm install** within the project folder
